CREATE DATABASE QLBH
USE QLBH

-- TAO TABLE
CREATE TABLE KHACHHANG(
	MAKH CHAR(4) NOT NULL
	, HOTEN VARCHAR(40)
	, DCHI VARCHAR(50)
	, SODT VARCHAR(20)
	, NGSINH SMALLDATETIME
	, DOANHSO MONEY
	, NGDK SMALLDATETIME
)
CREATE TABLE NHANVIEN(
	MANV CHAR(4) NOT NULL
	, HOTEN VARCHAR(40)
	, SODT VARCHAR(20)
	, NGVL SMALLDATETIME
)
CREATE TABLE SANPHAM(
	MASP CHAR(4) NOT NULL
	, TENSP VARCHAR(40)
	, DVT VARCHAR(20)
	, NUOCSX VARCHAR(40)
	, GIA MONEY
)
CREATE TABLE HOADON(
	SOHD INT NOT NULL
	, NGHD SMALLDATETIME
	, MAKH CHAR(4)
	, MANV CHAR(4)
	, TRIGIA MONEY
)
CREATE TABLE CTHD(
	SOHD INT NOT NULL
	, MASP CHAR(4) 
	, SL INT
)

-- TAO RANG BUOC
ALTER TABLE CTHD 
ALTER COLUMN MASP CHAR(4) NOT NULL

-- TAO PRIMARY KEY
ALTER TABLE KHACHHANG 
ADD CONSTRAINT PK_KHACHHANG PRIMARY KEY(MAKH)

ALTER TABLE NHANVIEN 
ADD CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV)

ALTER TABLE SANPHAM 
ADD CONSTRAINT PK_SANPHAM PRIMARY KEY(MASP)

ALTER TABLE HOADON 
ADD CONSTRAINT PK_HOADON PRIMARY KEY(SOHD)

ALTER TABLE CTHD 
ADD CONSTRAINT PK_CTHD PRIMARY KEY(SOHD, MASP)

-- TAO FOREIGN KEY
ALTER TABLE HOADON 
ADD CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)  

ALTER TABLE HOADON 
ADD CONSTRAINT FK_HOADON_NHANVIEN FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)

ALTER TABLE CTHD
ADD CONSTRAINT FK_CTHD_SANPHAM FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP)

ALTER TABLE CTHD
ADD CONSTRAINT FK_CTHD_HOADON FOREIGN KEY(SOHD) REFERENCES HOADON(SOHD)