CREATE DATABASE QLGV
USE QLGV

-- TAO TABLE
CREATE TABLE KHOA(
	MAKHOA VARCHAR(4) NOT NULL
	, TENKHOA VARCHAR(40)
	, NGTLAP SMALLDATETIME
	, TRGKHOA CHAR(4)
)
CREATE TABLE MONHOC(
	MAMH VARCHAR(10) NOT NULL
	, TENMH VARCHAR(40)
	, TCLT TINYINT
	, TCTH TINYINT
	, MAKHOA VARCHAR(4) 
)
CREATE TABLE DIEUKIEN(
	MAMH VARCHAR(10) NOT NULL
	, MAMH_TRUOC VARCHAR(10) NOT NULL
)
CREATE TABLE GIAOVIEN(
	MAGV CHAR(4) NOT NULL
	, HOTEN VARCHAR(40)
	, HOCVI VARCHAR(10)
	, HOCHAM VARCHAR(10)
	, GIOITINH VARCHAR(3)
	, NGSINH SMALLDATETIME
	, NGVL SMALLDATETIME
	, HESO NUMERIC(4,2)
	, MUCLUONG MONEY
	, MAKHOA VARCHAR(4) 
)
CREATE TABLE LOP(
	MALOP CHAR(3) NOT NULL
	, TENLOP VARCHAR(40)
	, TRGLOP CHAR(5)
	, SISO TINYINT
	, MAGVCN CHAR(4) 
)
CREATE TABLE HOCVIEN(
	MAHV CHAR(5) NOT NULL
	, HO VARCHAR(40)
	, TEN VARCHAR(10)
	, NGSINH SMALLDATETIME
	, GIOITINH VARCHAR(3)
	, NOISINH VARCHAR(40)
	, MALOP CHAR(3) 
)
CREATE TABLE GIANGDAY(
	MALOP CHAR(3) NOT NULL
	, MAMH VARCHAR(10) NOT NULL
	, MAGV CHAR(4) 
	, HOCKY TINYINT
	, NAM SMALLINT
	, TUNGAY SMALLDATETIME
	, DENNGAY SMALLDATETIME
)
CREATE TABLE KETQUATHI(
	MAHV CHAR(5) NOT NULL
	, MAMH VARCHAR(10) NOT NULL
	, LANTHI TINYINT NOT NULL
	, NGTHI SMALLDATETIME
	, DIEM NUMERIC(4,2)
	, KQUA VARCHAR(10)
)

-- TAO PRIMARY KEY
ALTER TABLE KHOA
ADD CONSTRAINT PK_KHOA PRIMARY KEY(MAKHOA)

ALTER TABLE MONHOC
ADD CONSTRAINT PK_MONHOC PRIMARY KEY(MAMH)

ALTER TABLE DIEUKIEN
ADD CONSTRAINT PK_DIEUKIEN PRIMARY KEY(MAMH, MAMH_TRUOC)

ALTER TABLE GIAOVIEN
ADD CONSTRAINT PK_GIAOVIEN PRIMARY KEY(MAGV)

ALTER TABLE LOP
ADD CONSTRAINT PK_LOP PRIMARY KEY(MALOP)

ALTER TABLE HOCVIEN
ADD CONSTRAINT PK_HOCVIEN PRIMARY KEY(MAHV)

ALTER TABLE GIANGDAY
ADD CONSTRAINT PK_GIANGDAY PRIMARY KEY(MALOP, MAMH)

ALTER TABLE KETQUATHI
ADD CONSTRAINT PK_KETQUATHI PRIMARY KEY(MAHV, MAMH, LANTHI)

-- TAO FOREIGN KEY
ALTER TABLE KHOA
ADD CONSTRAINT FK_KHOA_GIAOVIEN FOREIGN KEY(TRGKHOA) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE MONHOC
ADD CONSTRAINT FK_MONHOC_KHOA FOREIGN KEY(MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE DIEUKIEN
ADD CONSTRAINT FK_DIEUKIEN_MONHOC FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH)

ALTER TABLE GIAOVIEN
ADD CONSTRAINT FK_GIAOVIEN_KHOA FOREIGN KEY(MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_GIAOVIEN FOREIGN KEY(MAGVCN) REFERENCES GIAOVIEN(MAGV)
ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_HOCVIEN FOREIGN KEY(TRGLOP) REFERENCES HOCVIEN(MAHV)

ALTER TABLE HOCVIEN
ADD CONSTRAINT FK_HOCVIEN_LOP FOREIGN KEY(MALOP) REFERENCES LOP(MALOP)

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GIANGDAY_LOP FOREIGN KEY(MALOP) REFERENCES LOP(MALOP)
ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GIANGDAY_MONHOC FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH)
ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GIANGDAY_GIAOVIEN FOREIGN KEY(MAGV) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_KETQUATHI_HOCVIEN FOREIGN KEY(MAHV) REFERENCES HOCVIEN(MAHV)
ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_KETQUATHI_MONHOC FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH)